####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################
# https://github.com/ashwinvandijk/home-assistant
homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  internal_url: http://hass.foobar.io

  whitelist_external_dirs:
    - /config
    - /share

  customize: !include customize.yaml

  #
  # Packages in Home Assistant provide a way to bundle different component’s configuration together.
  # 
  # https://www.home-assistant.io/docs/configuration/packages/
  #
  packages: !include_dir_named packages

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 10.0.1.0/24
      allow_bypass_login: true
    - type: homeassistant

# Discover some devices automatically
discovery:
  ignore:
    - homekit

