####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################
# https://github.com/ashwinvandijk/home-assistant
homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  internal_url: http://hass.foobar.io

  whitelist_external_dirs:
    - /config
    - /share

  customize: !include_dir_merge_named customize
  packages: !include_dir_merge_named packages

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 10.0.1.0/24
      allow_bypass_login: true
    - type: homeassistant

# DO THIS: https://www.home-assistant.io/docs/configuration/splitting_configuration/
    
lovelace:
  mode: yaml

  resources: !include lovelace/resources.yaml

# camera streaming
stream:

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/hassio/
hassio:

#https://home-assistant.io/components/history/
history:

logger: !include includes/logger.yaml

# Track the sun
sun:

http:
  use_x_forwarded_for: true
  trusted_proxies: 10.0.1.20

# Text to speech
tts:
  - platform: google_translate
    language: nl
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://10.0.1.200:8123
    service_name: google_say

group: !include_dir_merge_named group
automation: !include_dir_merge_list automation
script: !include_dir_merge_named script
scene: !include_dir_merge_list scene

# binary_sensor: !include_dir_merge_list binary_sensor
# climate: !include_dir_merge_list climate
# input_boolean: !include_dir_merge_named input_boolean
# input_datetime: !include_dir_merge_named input_datetime
# input_number: !include_dir_merge_named input_number
# input_select: !include_dir_merge_named input_select
# light: !include_dir_merge_list light
# media_player: !include_dir_merge_list media_player
# sensor: !include_dir_merge_list sensor
# zone: !include_dir_merge_list zone

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

#samsungtv:
#  - host: !secret samsungtv_ip
#    name: Samsung TV
#    turn_on_action:
#      - service: wake_on_lan.send_magic_packet
#        data:
#          mac: !secret samsungtv_mac

# https://www.home-assistant.io/integrations/zwave/
zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00

# https://github.com/StyraHem/ShellyForHASS
shelly:

# Enables person component
person:
  - name: Pascal
    id: pascal
    user_id: a7fee9cc3e674efba3b1a8cd5eb461af
    device_trackers:
      - device_tracker.pascals_iphone_2

# Enables system health
system_health:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  reporting: false
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - homekit

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

################################################
## Notify
################################################
notify:
  - name: homeassistant
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: all_devices
    platform: group
    services:
      - service: mobile_app_pprins

sensor:
  # https://www.home-assistant.io/integrations/dsmr/
  - platform: dsmr

  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  - platform: dnsip

  - platform: afvalbeheer
    wastecollector: MijnAfvalwijzer
    resources:
      - gft
      - papier
      - pmd
    postcode: !secret afvalbeheer_postcode
    streetnumber: !secret afvalbeheer_streetnumber
    upcomingsensor: 1
    nameprefix: 1
    builtinicons: 1
    dutch: 1

  - platform: template
    sensors:
      afval:
        entity_id: sensor.ophaalkalender_vandaag
        friendly_name: Afval vandaag
        icon_template: mdi:delete
        value_template: >
          {% if is_state('sensor.mijnafvalwijzer_vandaag', 'pmd') %}
            Deze avond pmd buiten zetten!
          {% elif is_state('sensor.mijnafvalwijzer_vandaag', 'gft') %}
            Deze avond gft buiten zetten!
          {% elif is_state('sensor.mijnafvalwijzer_vandaag', 'papier') %}
            Deze avond papier en karton buiten zetten!
          {% endif %}

  - platform: template
    sensors:
      solar_power:
        friendly_name: 'Solar power production'
        unit_of_measurement: 'W'
        value_template: >-
          {{ (1000 * (states("sensor.power_production") | float)) | int }}
      grid_power_consumption:
        friendly_name: 'Grid power consumption'
        unit_of_measurement: 'W'
        value_template: >-
          {{ (1000 * (states("sensor.power_consumption") | float)) | int }}
      grid_power_production:
        friendly_name: 'Grid power production'
        unit_of_measurement: 'W'
        value_template: >-
          {{ (1000 * (states("sensor.power_production") | float)) | int }}
