####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  whitelist_external_dirs:
    - /config
    - /share

  packages: !include_dir_named integrations

  customize: !include customize.yaml

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 10.0.1.0/24
      allow_bypass_login: true
    - type: homeassistant

# DO THIS: https://www.home-assistant.io/docs/configuration/splitting_configuration/
    
####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

lovelace:
  mode: yaml
  
  resources:
    - type: module
      url: /hacsfiles/custom-header/custom-header.js
    - type: module
      url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    - type: module
      url: /hacsfiles/bignumber-card/bignumber-card.js
    - type: module
      url: /hacsfiles/text-element/text-element.js
    - type: module
      url: /hacsfiles/mini-media-player/mini-media-player-bundle.js

# Configure a default setup of Home Assistant (frontend, api, etc)
# default_config:

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/hassio/
hassio:

#https://home-assistant.io/components/history/
history:

logger: !include includes/system/logger.yaml

http:
  base_url: http://hass.foobar.io
  use_x_forwarded_for: true
  trusted_proxies: 10.0.1.20

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

#samsungtv:
#  - host: !secret samsungtv_ip
#    name: Samsung TV
#    turn_on_action:
#      - service: wake_on_lan.send_magic_packet
#        data:
#          mac: !secret samsungtv_mac

# Enables person component
person:

# Enables system health
system_health:

# Checks for available updates
updater:
  reporting: false

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  - platform: dnsip

  - platform: afvalbeheer
    wastecollector: MijnAfvalwijzer
    resources:
      - gft
      - papier
      - pmd
    postcode: !secret afvalbeheer_postcode
    streetnumber: !secret afvalbeheer_streetnumber
