# ======================================================================
#
# ui-lovelace.yaml
#
# ======================================================================

title: Home

# Custom header configuration
# https://maykar.github.io/custom-header/#configuration/main
custom_header:
  compact_mode: true
  hide_help: true

views:
  - !include lovelace/10-toon.yaml
