# ======================================================================
#
# ui-lovelace.yaml
#
# ======================================================================

title: Home

# Custom header configuration
# https://maykar.github.io/custom-header/#configuration/main
custom_header:
  compact_mode: true
  hide_help: true

views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/smartmeter.yaml
  - !include lovelace/views/camera.yaml
#  - !include lovelace/views/toon.yaml
  - !include lovelace/views/lights.yaml
  - !include lovelace/views/streams.yaml
