# ======================================================================
#
# ui-lovelace.yaml
#
# ======================================================================

title: Home

# Custom header configuration
# https://maykar.github.io/custom-header/#configuration/main
custom_header:
  compact_mode: true
  hide_help: true

views:
  - !include lovelace/dashboard.yaml
#  - !include lovelace/toon.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/streams.yaml
