- platform: darksky
  api_key: !secret darksky_api_key
  name: Zwartewaal
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  monitored_conditions:
    - icon
    - summary
    - humidity
    - temperature
    - temperature_high
    - temperature_low
    - daily_summary

- platform: tautulli
  api_key: !secret tautulli_api_key
  host: !secret tautulli_host
  port: !secret tautulli_port
  monitored_conditions:
    - title
    - platform
    - player
    - ip_address

- platform: template
  sensors:
    tautulli_count_total:
      friendly_name: 'Total streams'
      value_template: '{{ states.sensor.tautulli.attributes.stream_count_transcode }}'    
    tautulli_count_transcode:
      friendly_name: 'Transcoded streams'
      value_template: '{{ states.sensor.tautulli.attributes.stream_count_transcode }}'
    tautulli_direct_plays:
      friendly_name: 'Direct Plays'
      value_template: '{{ states.sensor.tautulli.attributes.stream_count_direct_play }}'
    tautulli_direct_streams:
      friendly_name: 'Direct Streams'
      value_template: '{{ states.sensor.tautulli.attributes.stream_count_direct_stream }}'
    tautulli_lan:
      friendly_name: "LAN Bandwidth"
      entity_id: sensor.tautulli
      unit_of_measurement: 'Mbps'
      value_template: "{{states.sensor.tautulli.attributes.lan_bandwidth|float / 1000}}"
    tautulli_wan:
      friendly_name: "WAN Bandwidth"
      entity_id: sensor.tautulli
      unit_of_measurement: 'Mbps'
      value_template: "{{states.sensor.tautulli.attributes.wan_bandwidth|float / 1000}}"
    tautulli_total:
      friendly_name: "Total Bandwidth"
      entity_id: sensor.tautulli
      unit_of_measurement: 'Mbps'
      value_template: "{{states.sensor.tautulli.attributes.total_bandwidth|float / 1000}}"

# https://www.home-assistant.io/integrations/dsmr/
- platform: dsmr

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: dnsip

- platform: afvalbeheer
  wastecollector: MijnAfvalwijzer
  resources:
    - gft
    - papier
    - pmd
  postcode: !secret afvalbeheer_postcode
  streetnumber: !secret afvalbeheer_streetnumber
  upcomingsensor: 1
  nameprefix: 1
  builtinicons: 1
  dutch: 1

- platform: template
  sensors:
    afval:
      entity_id: sensor.ophaalkalender_vandaag
      friendly_name: Afval vandaag
      icon_template: mdi:delete
      value_template: >
        {% if is_state('sensor.mijnafvalwijzer_vandaag', 'pmd') %}
          Deze avond pmd buiten zetten!
        {% elif is_state('sensor.mijnafvalwijzer_vandaag', 'gft') %}
          Deze avond gft buiten zetten!
        {% elif is_state('sensor.mijnafvalwijzer_vandaag', 'papier') %}
          Deze avond papier en karton buiten zetten!
        {% endif %}

- platform: template
  sensors:
    solar_power:
      friendly_name: 'Solar power production'
      unit_of_measurement: 'W'
      value_template: >-
        {{ (1000 * (states("sensor.power_production") | float)) | int }}
    grid_power_consumption:
      friendly_name: 'Grid power consumption'
      unit_of_measurement: 'W'
      value_template: >-
        {{ (1000 * (states("sensor.power_consumption") | float)) | int }}
    grid_power_production:
      friendly_name: 'Grid power production'
      unit_of_measurement: 'W'
      value_template: >-
        {{ (1000 * (states("sensor.power_production") | float)) | int }}
