automation:
  - id: '1590166358190'
    alias: test
    description: test
    trigger:
      - event: start
        platform: homeassistant
      - entity_id: media_player.nest_hub_keuken
        for: 00:01:00
        platform: state
        to: idle
    condition: []
    action:
      service: cast.show_lovelace_view
      data:
        entity_id: media_player.nest_hub_keuken
        dashboard_path: lovelace
        view_path: dashboard
